// BEGIN CCCT SECTION
/* -------------------------------------------------------------------------
 Copyright (C) 2013 Intel Mobile Communications GmbH
 
      Sec Class: Intel Confidential (IC)
 ----------------------------------------------------------------------
 Revision Information:
    $File name:  /mhw_drv_src/memory_management/mem/scatterfile/tools/prggen/mem_description_partition.h $
 ----------------------------------------------------------------------
 by CCCT (0.12e)
 ---------------------------------------------------------------------- */
// END CCCT SECTION

// partition description file

#if defined(MMAP_INCLUDE_PARTITION_INFO)
// partition attributes

// partition image types
MMAP_UPDATE_PARTITION_INFO_IT(PSI_IMAGE,            BOOTUP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(SLB_IMAGE,            BOOTUP_SLB_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(PSI_MIRROR,           BOOTUP_SLB_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(BOOTROM_PATCH_MIRROR, BOOTUP_SLB_IMAGE)

MMAP_UPDATE_PARTITION_INFO_IT(NVM_STATIC_CALIB,   SDS_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(NVM_STATIC_FIX,     SDS_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(NVM_DYNAMIC,        SDS_IMAGE)

MMAP_UPDATE_PARTITION_INFO_IT(PARTITION_TABLE,    RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(BAD_BLOCK_TABLE,    RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(RAW_NAND_IMAGE,     RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(PREFLASH_IMAGE,     RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(DYN_SDS_IMAGE,      RAW_IMAGE)

MMAP_UPDATE_PARTITION_INFO_IT(FTL_STARTUP_DISC,   FTL_IMAGE)

MMAP_UPDATE_PARTITION_INFO_IT(ROOT_DISC,          FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USBRO,              FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CUSTOMIZATION_DISC, FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USER_DISC,          FAT_IMAGE)

MMAP_UPDATE_PARTITION_INFO_IT(DSP_IMAGE,          BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CODE_IMAGE,         BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CUSTOMIZATION_DATA, BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CDS_IMAGE,          BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(UA_IMAGE,           BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(PAGING_IMAGE,       BBR_IMAGE)


MMAP_UPDATE_PARTITION_INFO_IT(BOOTROM_PATCH,      BOOTUP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(UCODE_PATCH,        BOOTUP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(VRL,                BOOTUP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CERTIFICATE_DATA,   BOOTUP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(VRL,                BOOTUP_IMAGE)

#if defined(FEAT_FLASH_WRITE_PROTECT_ENABLED)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(PSI_IMAGE, POWER_ON_WP_NORMAL_MODE, TRUE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(PSI_IMAGE, POWER_ON_WP_UPDATE_MODE, TRUE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(BOOTROM_PATCH,PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(UCODE_PATCH,PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(VRL, PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(PSI_MIRROR, PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(BOOTROM_PATCH_MIRROR, PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(SLB_IMAGE,PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(PARTITION_TABLE,PSI_IMAGE)
  MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(CERTIFICATE_DATA, PSI_IMAGE)
#endif

// partition options
#if !defined(DEFAULT_ACCEPTABLE_BIT_ERRORS)
  #define DEFAULT_ACCEPTABLE_BIT_ERRORS     0x4
#endif  /* DEFAULT_ACCEPTABLE_BIT_ERRORS */

MMAP_UPDATE_PARTITION_INFO_OPT(SLB_IMAGE, LOADMAP, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(SLB_IMAGE, VERIFICATION_REQUIRED, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(SLB_IMAGE, ALIGNMENT, 0xC)
MMAP_UPDATE_PARTITION_INFO_OPT(SLB_IMAGE, ACCEPTABLE_BIT_ERRORS, DEFAULT_ACCEPTABLE_BIT_ERRORS)

MMAP_UPDATE_PARTITION_INFO_OPT(CODE_IMAGE, LOADMAP, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(CODE_IMAGE, VERIFICATION_REQUIRED, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(CODE_IMAGE, COPYTORAM, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(CODE_IMAGE, READONLYIMAGE, TRUE);
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(DSP_IMAGE,            CODE_IMAGE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(CDS_IMAGE,            CODE_IMAGE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(CERTIFICATE_DATA,     CODE_IMAGE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(USBRO,                CODE_IMAGE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(PAGING_IMAGE,         CODE_IMAGE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(UA_IMAGE,             CODE_IMAGE)
MMAP_UPDATE_PARTITION_INFO_OPT(PAGING_IMAGE, ALIGNMENT, 0xC)

MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_PLP_RUN_CHECK_DISK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_ACCESS_INTERNAL, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_ACCESS_EXTERNAL, TRUE)
//MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, ACCEPTABLE_BIT_ERRORS, DEFAULT_ACCEPTABLE_BIT_ERRORS)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(USER_DISC,            ROOT_DISC)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(CUSTOMIZATION_DISC,   ROOT_DISC)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_SYSTEM_DISK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(USER_DISC, FS_DEVICE_NOT_SYSTEM_DISK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(CUSTOMIZATION_DISC, FS_DEVICE_NOT_SYSTEM_DISK, TRUE)

MMAP_UPDATE_PARTITION_INFO_OPT(BAD_BLOCK_TABLE, READONLYIMAGE, TRUE)

#if defined(FEAT_OPM_MEM_SECTION_NVM_MIRROR)
MMAP_UPDATE_PARTITION_INFO_OPT(NVM_STATIC_CALIB, COPYTORAM, TRUE)
//MMAP_UPDATE_PARTITION_INFO_OPT(NVM_STATIC_CALIB, PRESERVE_PARTITION, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(NVM_STATIC_FIX,       NVM_STATIC_CALIB)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(NVM_DYNAMIC,          NVM_STATIC_CALIB)
#endif

MMAP_UPDATE_MEMORYMAP_INFO_CLASS(PSI_IMAGE, BOOT_CORE_PSI_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SLB_IMAGE, BOOT_CORE_SLB_CLASS)

#endif  /* MMAP_INCLUDE_PARTITION_INFO */
