// BEGIN CCCT SECTION
/* -------------------------------------------------------------------------
 Copyright (C) 2013 Intel Mobile Communications GmbH
 
      Sec Class: Intel Confidential (IC)
 ----------------------------------------------------------------------
 Revision Information:
    $File name:  /mhw_drv_src/memory_management/mem/scatterfile/tools/prggen/mem_description_memorymap.h $
 ----------------------------------------------------------------------
 by CCCT (0.12e)
 ---------------------------------------------------------------------- */
// END CCCT SECTION

// mem_description_memoymap.h

#if defined(MMAP_INCLUDE_MEMORYMAP_INFO)
// refer: FlsFile.h
#if defined(FEAT_SLB_IN_PCM) && !defined(FEAT_NAND_PRGGEN) && !defined(FEAT_FTLE_PRGGEN)
  MMAP_UPDATE_MEMORYMAP_INFO_CLASS(PSI_IMAGE,         BOOT_CORE_SLB_CLASS)
#endif
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SLB_IMAGE,           BOOT_CORE_SLB_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(PSI_RAM,             BOOT_CORE_PSI_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(EBL,                 BOOT_CORE_EBL_CLASS)

MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SYSTEM,              CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USERDATA,            CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CACHE,               CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(ROOT_DISC,           ROOT_DISK_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USBRO,               USER_DISK_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CUSTOMIZATION_DISC,  CUST_DISK_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USER_DISC,           USER_DISK_CLASS)

MMAP_UPDATE_MEMORYMAP_INFO_CLASS(DSP_IMAGE,          DSP_SW_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CODE_IMAGE,         CODE_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CUSTOMIZATION_DATA, CODE_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CDS_IMAGE,          CODE_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(UA_IMAGE,           CODE_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(PAGING_IMAGE,       CODE_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CERTIFICATE_DATA,   CODE_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(VLX,                CODE_CLASS)

MMAP_UPDATE_MEMORYMAP_INFO_CLASS(PSI_IMAGE, BOOT_CORE_PSI_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SLB_IMAGE, BOOT_CORE_SLB_CLASS)
#endif  /* MMAP_INCLUDE_MEMORYMAP_INFO */
