# This enables the wpa wireless driver
BOARD_HOSTAPD_DRIVER ?= NL80211
BOARD_WPA_SUPPLICANT_DRIVER ?= NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB ?= private_lib_driver_cmd
WPA_SUPPLICANT_VERSION := VER_2_1_DEVEL_WCS

# Enabling iwlwifi
BOARD_USING_INTEL_IWL := true
INTEL_IWL_USE_SYSTEM_COMPAT_MOD_BUILD := y
INTEL_IWL_COMPAT_INSTALL_DIR := updates

#fw target out dir
TARGET_OUT_WLAN_FW := $(TARGET_OUT_VENDOR)/firmware

