// BEGIN CCCT SECTION
/* -------------------------------------------------------------------------
 Copyright (C) 2013 Intel Mobile Communications GmbH
 
      Sec Class: Intel Confidential (IC)
 ----------------------------------------------------------------------
 Revision Information:
    $File name:  /mhw_drv_src/memory_management/mem/scatterfile/tools/prggen/category/candroidc/mem_android_description_partition.h $
 ----------------------------------------------------------------------
 by CCCT (0.12e)
 ---------------------------------------------------------------------- */
// END CCCT SECTION

// partition description file

#if defined(MMAP_INCLUDE_PARTITION_INFO)
// partition attributes
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(BCB, GPT_PARTITION, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(BCB, GPT_TYPE_GUID_a, TRUE)

MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(BOOT_IMG, BCB)
#if defined(FEAT_FLASH_WRITE_PROTECT_ENABLED)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(BOOT_IMG, POWER_ON_WP_NORMAL_MODE, TRUE)
//MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(BOOT_IMG, POWER_ON_WP_UPDATE_MODE, TRUE)
#endif
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(RECOVERY_IMG,         BOOT_IMG)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(RECOVERY_IMG_MIRROR,  BOOT_IMG)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(KDUMP_IMG,            BOOT_IMG)

MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(LINUX_NVM_FS, GPT_PARTITION, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(LINUX_NVM_FS, GPT_TYPE_GUID_b, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(SYSTEM,     LINUX_NVM_FS)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(USERDATA,   LINUX_NVM_FS)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(SECURITY_IMAGE,   USERDATA)


MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(CACHE,      LINUX_NVM_FS)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(USER_DISC,      LINUX_NVM_FS)

MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(DSP_IMAGE, GPT_PARTITION, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(DSP_IMAGE, GPT_TYPE_GUID_a, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(DSP_IMAGE, GPT_TYPE_GUID_b, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(NVM_STATIC_FIX,        DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(NVM_DYNAMIC,           DSP_IMAGE)

MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(FW_UPDATE,        BCB)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(COMBO_RECOVERY_MIRROR, BCB)
#if defined(FEAT_FLASH_WRITE_PROTECT_ENABLED)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(DSP_IMAGE, POWER_ON_WP_NORMAL_MODE, TRUE)
//MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(DSP_IMAGE, POWER_ON_WP_UPDATE_MODE, TRUE)
#endif
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(NVM_STATIC_CALIB,      DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(CODE_IMAGE, DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(VLX,        DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(MOBILEVISOR,     DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(MOBILEVISOR_CONFIG,    DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(RECOVERY,        BOOT_IMG)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(COMBO_RECOVERY, BOOT_IMG)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(SECURE_VM,        DSP_IMAGE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(MODEM_IMAGE,      DSP_IMAGE)

// User disc extended partitions enabled on need basis
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(USER_DISC_EXTEND2, FW_UPDATE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(USER_DISC_EXTEND3, FW_UPDATE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(USER_DISC_EXTEND4, FW_UPDATE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE_COPY(STARTUP_IMAGE,   LINUX_NVM_FS)
#if defined(FEAT_FLASH_WRITE_PROTECT_ENABLED)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(PRIMARY_GPT, POWER_ON_WP_NORMAL_MODE, TRUE)
//MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(PRIMARY_GPT, POWER_ON_WP_UPDATE_MODE, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(SECONDARY_GPT, POWER_ON_WP_NORMAL_MODE, TRUE)
MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(STARTUP_IMAGE, POWER_ON_WP_NORMAL_MODE, TRUE)
//MMAP_UPDATE_PARTITION_INFO_ATTRIBUTE(STARTUP_IMAGE, POWER_ON_WP_UPDATE_MODE, TRUE)
#endif

// partition image types
MMAP_UPDATE_PARTITION_INFO_IT(ROOT_DISC,          FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CUSTOMIZATION_DISC, FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USER_DISC,          FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(SYSTEM,             FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USERDATA,           FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USER_DISC_EXTEND2,  FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USER_DISC_EXTEND3,  FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(USER_DISC_EXTEND4,  FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(CACHE,              FAT_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(VLX,                BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(MOBILEVISOR,        BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(MOBILEVISOR_CONFIG, BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(RECOVERY,           BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(COMBO_RECOVERY,     BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(COMBO_RECOVERY_MIRROR, BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(FW_UPDATE,          BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(SECURE_VM,          BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(LINUX_KERNEL,       BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(INITRD,             BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(INITRD_RECOVERY,    BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(BOOT_IMG,           BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(RECOVERY_IMG,       BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(RECOVERY_IMG_MIRROR,BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(KDUMP_IMG,          BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(NVM_STATIC_CALIB,   BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(MODEM_IMAGE,        BBR_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(SECURITY_IMAGE,     FAT_IMAGE)

#if defined(FEAT_FTLE_PRGGEN)
/* Assuming GPT support is always present for EMMC */
MMAP_UPDATE_PARTITION_INFO_IT(PARTITION_TABLE,    BOOTUP_IMAGE)
#endif
MMAP_UPDATE_PARTITION_INFO_IT(PRIMARY_GPT,        RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(SECONDARY_GPT,      RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(LINUX_NVM_FS,       RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(BCB,                RAW_IMAGE)
MMAP_UPDATE_PARTITION_INFO_IT(FW_UPDATE,          RAW_IMAGE)
// partition options
#if !defined(DEFAULT_ACCEPTABLE_BIT_ERRORS)
  #define DEFAULT_ACCEPTABLE_BIT_ERRORS     0x4
#endif  /* DEFAULT_ACCEPTABLE_BIT_ERRORS */

MMAP_UPDATE_PARTITION_INFO_OPT(VLX, READONLYIMAGE, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(VLX, LOADMAP, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(VLX, VERIFICATION_REQUIRED, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(VLX, COPYTORAM, TRUE)
#if !defined(FEAT_FTLE_PRGGEN)
MMAP_UPDATE_PARTITION_INFO_OPT(VLX, RO_BIT_CORRECTION_OK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(VLX, ACCEPTABLE_BIT_ERRORS, DEFAULT_ACCEPTABLE_BIT_ERRORS)
#endif

MMAP_UPDATE_PARTITION_INFO_OPT_COPY(BOOT_IMG,             VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(RECOVERY_IMG,         VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(RECOVERY_IMG_MIRROR,  VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(KDUMP_IMG,            VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(LINUX_KERNEL,         VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(INITRD,               VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(INITRD_RECOVERY,      VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(MOBILEVISOR,          VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(MOBILEVISOR_CONFIG,   VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(RECOVERY,             VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(COMBO_RECOVERY,       VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(COMBO_RECOVERY_MIRROR,VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(SECURE_VM,            VLX)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(MODEM_IMAGE,          VLX)
MMAP_UPDATE_PARTITION_INFO_OPT(UCODE_PATCH, LOADMAP, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(UCODE_PATCH, VERIFICATION_REQUIRED, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(STARTUP_IMAGE, LOADMAP, TRUE)

MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_ACCESS_INTERNAL, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_ACCESS_EXTERNAL, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, ACCEPTABLE_BIT_ERRORS, DEFAULT_ACCEPTABLE_BIT_ERRORS)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_NOT_SYSTEM_DISK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_SYSTEM_DISK, FALSE)
MMAP_UPDATE_PARTITION_INFO_OPT(ROOT_DISC, FS_DEVICE_PLP_RUN_CHECK_DISK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(USER_DISC,            ROOT_DISC)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(CUSTOMIZATION_DISC,   ROOT_DISC)

MMAP_UPDATE_PARTITION_INFO_OPT(CERTIFICATE_DATA, LOADMAP, FALSE)
MMAP_UPDATE_PARTITION_INFO_OPT(CERTIFICATE_DATA, VERIFICATION_REQUIRED, FALSE)
MMAP_UPDATE_PARTITION_INFO_OPT(CERTIFICATE_DATA, COPYTORAM, FALSE)
#if defined(NVM_PARTITION_SEGGREGATION)
MMAP_UPDATE_PARTITION_INFO_OPT(NVM_STATIC_CALIB, COPYTORAM, FALSE)
MMAP_UPDATE_PARTITION_INFO_OPT(NVM_STATIC_CALIB, BACKUP_DATA_REQUIRED, TRUE) //set NVM need to be backup
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(NVM_STATIC_FIX,       NVM_STATIC_CALIB)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(NVM_DYNAMIC,          NVM_STATIC_CALIB)
#endif

#endif  /* MMAP_INCLUDE_PARTITION_INFO */
