// BEGIN CCCT SECTION
/* -------------------------------------------------------------------------
 Copyright (C) 2013 Intel Mobile Communications GmbH
 
      Sec Class: Intel Confidential (IC)
 ----------------------------------------------------------------------
 Revision Information:
    $File name:  /mhw_drv_src/memory_management/mem/scatterfile/tools/prggen/category/candroidc/mem_android_description_memorymap.h $
 ----------------------------------------------------------------------
 by CCCT (0.12e)
 ---------------------------------------------------------------------- */
// END CCCT SECTION

// mem_description_memoymap.h

#if defined(MMAP_INCLUDE_MEMORYMAP_INFO)
// refer: FlsFile.h
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CERTIFICATE_DATA,     CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SYSTEM,               CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USERDATA,             CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CACHE,                CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(ROOT_DISC,            CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CUSTOMIZATION_DISC,   CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USER_DISC,            CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SECURITY_IMAGE,       CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(VLX,                  CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(BOOT_IMG,             CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(RECOVERY_IMG,         CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(RECOVERY_IMG_MIRROR,  CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(KDUMP_IMG,            CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(LINUX_KERNEL,         CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(INITRD,               CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(INITRD_RECOVERY,      CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(NVM_STATIC_CALIB,     CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(NVM_STATIC_FIX,       CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(NVM_DYNAMIC,          CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(LINUX_NVM_FS,         CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(MOBILEVISOR,          CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(MOBILEVISOR_CONFIG,   CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(RECOVERY,             CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(COMBO_RECOVERY,       CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(COMBO_RECOVERY_MIRROR,CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(FW_UPDATE,            CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(SECURE_VM,            CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(BOOTROM_PATCH,        CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(VRL,                  BOOT_CORE_PSI_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(PSI_MIRROR,           CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(BOOTROM_PATCH_MIRROR, CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(UCODE_PATCH,          CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(MODEM_IMAGE,          CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(STARTUP_IMAGE,        CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CUSTOMIZATION_DISC_EXTEND1,       CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CUSTOMIZATION_DISC_EXTEND2,       CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(CUSTOMIZATION_DISC_EXTEND3,       CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USER_DISC_EXTEND2,    CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USER_DISC_EXTEND3,    CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(USER_DISC_EXTEND4,    CUST_CLASS)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(BCB,                  CUST_CLASS)
#if defined(VMM_MOBILEVISOR)
MMAP_UPDATE_MEMORYMAP_INFO_CLASS(DSP_IMAGE,           CUST_CLASS)
#endif
#endif  /* MMAP_INCLUDE_MEMORYMAP_INFO */
