// BEGIN CCCT SECTION
/* -------------------------------------------------------------------------
 Copyright (C) 2013 Intel Mobile Communications GmbH
 
      Sec Class: Intel Confidential (IC)
 ----------------------------------------------------------------------
 Revision Information:
    $File name:  /mhw_drv_src/memory_management/mem/scatterfile/tools/prggen/category/candroidc/mem_android_description_tags.h $
 ----------------------------------------------------------------------
 by CCCT (0.12e)
 ---------------------------------------------------------------------- */
// END CCCT SECTION

// tags description file

#if defined(MMAP_INCLUDE_MEMORYMAP_INFO)
// declare tags first
  // for android-ip compatibility
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(LINUX_KERNEL, "LINUX_KERNEL")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(INITRD, "INITRD")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(INITRD_RECOVERY, "INITRD_RECOVERY")
  
  // android on 6321 on-wards...
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(BOOT_IMG, "BOOT_IMG:1#47")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(RECOVERY_IMG, "RECOVERY_IMG")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(RECOVERY_IMG_MIRROR, "RECOVERY_IMG_MIRROR")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(KDUMP_IMG, "KDUMP_IMG")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(LINUX_NVM_FS, "LNX_NVM_FS:1#4C")
#if defined(FEAT_FTLE_PRGGEN)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(SYSTEM, "SYSTEM:1#44")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(CACHE, "CACHE:1#46")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(USERDATA, "USERDATA:1#45")
#endif
#if defined(FEAT_NAND_PRGGEN)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(ROOT_DISC, "SYSTEM")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC, "CACHE")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(USER_DISC, "USERDATA")
#endif
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(VLX, "VLX")
#if !defined(VMM_MOBILEVISOR)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(MOBILEVISOR, "MOBILEVISOR:1#1")
#else
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(CODE_IMAGE, "MOBILEVISOR:1#1")
#endif
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(MOBILEVISOR_CONFIG, "MV_CONFIG:1#73")
#if !defined(FEAT_OPM_MEM_SINGLE_FILE_RECOVERY) //TODO: Nandhini
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(RECOVERY, "RECOVERY:1#79")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(COMBO_RECOVERY, "COMBO_RECOVERY")
#else
  #if defined(LOLLIPOP_PARTITION_LAYOUT)
    MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC_EXTEND1, "RECOVERY:1#79")
    MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC_EXTEND2, "RECOVERY:2#79")
    MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC_EXTEND3, "RECOVERY:3#79")
  #else
    MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC_EXTEND1, "RECOVERY:1#77")
    MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC_EXTEND2, "RECOVERY:2#77")
    MMAP_UPDATE_MEMORYMAP_INFO_TAG(CUSTOMIZATION_DISC_EXTEND3, "RECOVERY:3#77")
  #endif
#endif
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(USER_DISC_EXTEND2, "CUST_APD:1#20")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(USER_DISC_EXTEND3, "CUST_ADF:1#21")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(USER_DISC_EXTEND4, "CUST_NVM:1#22")
  
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(FW_UPDATE, "FW_UPDATE:1#7A")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(COMBO_RECOVERY_MIRROR, "RECOVERY_MIRROR")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(SECURE_VM, "SECURE_VM:1#76")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(MODEM_IMAGE, "MODEM_IMG:1#72")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(VRL, "VRL:1#7B")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(PSI_MIRROR, "PSI_MIRROR:1#7C")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(BOOTROM_PATCH_MIRROR, "BOOTROM_PATCH_MIRROR:1#7D")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(BOOTROM_PATCH, "BM_PATCH:1#70")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(UCODE_PATCH, "UC_PATCH:1#71")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(STARTUP_IMAGE, "SPLASH_SCRN:1#D")
  MMAP_UPDATE_MEMORYMAP_INFO_TAG(SECURITY_IMAGE, "SEC_IMG:1#0A")
// then hex2fls rules
#if(ANDROID_OUTPUT_FLS)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG_H2F(MOBILEVISOR_CONFIG,
                                     FMT_STANDARD FMT_OUTPUT FMT_INPUT,
                                     V_STANDARD(MOBILEVISOR_CONFIG), ANDROID_OUTPUT_DIR, "mvconfig", MVCONFIG_BIN_INPUT_PATH)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG_H2F(CODE_IMAGE,
                                     FMT_STANDARD FMT_OUTPUT FMT_INPUT,
                                     V_STANDARD(CODE_IMAGE), ANDROID_OUTPUT_DIR, "mobilevisor", MOBILEVISOR_BIN_INPUT_PATH)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG_H2F(SECURE_VM,
                                     FMT_STANDARD FMT_OUTPUT FMT_INPUT,
                                     V_STANDARD(SECURE_VM), ANDROID_OUTPUT_DIR, "secvm", SECURE_VM_BIN_INPUT_PATH)
  MMAP_UPDATE_MEMORYMAP_INFO_TAG_H2F(BOOT_IMG,
                                     FMT_STANDARD FMT_OUTPUT FMT_INPUT,
                                     V_STANDARD(BOOT_IMG), ANDROID_OUTPUT_DIR, "bootimg", BOOT_IMG_BIN_INPUT_PATH)
#endif
#endif  /* MMAP_INCLUDE_MEMORYMAP_INFO */

