#!/system/bin/sh

#LOG_FILE=/data/tinyplaywave.log

# check input
if [ $# -lt 1 ] ; then
#echo "[tinyplaywav] not wav file to play!!" >> $LOG_FILE
exit 1
fi

# set parameter
WAV_FILE=$1

if [ $# -eq 2 ] ; then
# sleep some time
#echo "[tinyplaywav] sleep $2 s" >> $LOG_FILE
sleep $2
fi

# play wav file
#echo "[tinyplaywav] start play, wav file is: $WAV_FILE" >> $LOG_FILE
tinymix -D 0 "Playback Path" "SPK"
tinyplay $WAV_FILE -D 0 -d 0
