// BEGIN CCCT SECTION
/* -------------------------------------------------------------------------
 Copyright (C) 2013 Intel Mobile Communications GmbH
 
      Sec Class: Intel Confidential (IC)
 ----------------------------------------------------------------------
 Revision Information:
    $File name:  /mhw_drv_src/memory_management/mem/scatterfile/tools/prggen/category/cnokiac/mem_nokia_description_partition.h $
 ----------------------------------------------------------------------
 by CCCT (0.12e)
 ---------------------------------------------------------------------- */
// END CCCT SECTION

// partition description file

#if defined(MMAP_INCLUDE_PARTITION_INFO)
// partition image types
MMAP_UPDATE_MEMORYMAP_INFO_IT(PMM_PLAIN,     SDS_IMAGE)
MMAP_UPDATE_MEMORYMAP_INFO_IT(PMM_PROT,      SDS_IMAGE)
MMAP_UPDATE_MEMORYMAP_INFO_IT(SUSD,          FTL_IMAGE)
MMAP_UPDATE_MEMORYMAP_INFO_IT(PPM,           BBR_IMAGE)
MMAP_UPDATE_MEMORYMAP_INFO_IT(UPDAPP_IMAGE,  FTL_IMAGE)
MMAP_UPDATE_MEMORYMAP_INFO_IT(DYNSW,         BBR_IMAGE)

// partition options
#if !defined(DEFAULT_ACCEPTABLE_BIT_ERRORS)
  #define DEFAULT_ACCEPTABLE_BIT_ERRORS     0x4
#endif  /* DEFAULT_ACCEPTABLE_BIT_ERRORS */

MMAP_UPDATE_PARTITION_INFO_OPT(SUSD, ALLOW_UTA_BYTE_IF_ACCESS, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(SUSD, ACCEPTABLE_BIT_ERRORS, DEFAULT_ACCEPTABLE_BIT_ERRORS)

MMAP_UPDATE_PARTITION_INFO_OPT_COPY(PMM_PLAIN,    SUSD)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(PMM_PROT,     SUSD)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(PPM,          SUSD)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(UPDAPP_IMAGE, SUSD)
MMAP_UPDATE_PARTITION_INFO_OPT_COPY(DYNSW,        SUSD)

MMAP_UPDATE_PARTITION_INFO_OPT(PMM_PLAIN, SHORT_TIMEOUT, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(PMM_PROT, SHORT_TIMEOUT, TRUE)

MMAP_UPDATE_PARTITION_INFO_OPT(PPM, RO_BIT_CORRECTION_OK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(PPM, LOADMAP, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(PPM, COPYTORAM, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(PPM, READONLYIMAGE, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(PPM, VERIFICATION_REQUIRED, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(PPM, ALLOW_UTA_BLOCK_IF_ACCESS, TRUE)

MMAP_UPDATE_PARTITION_INFO_OPT(UPDAPP_IMAGE, ALLOW_UTA_BLOCK_IF_ACCESS, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(UPDAPP_IMAGE, ALLOW_UTA_BYTE_IF_ACCESS, FALSE)
MMAP_UPDATE_PARTITION_INFO_OPT(UPDAPP_IMAGE, RO_BIT_CORRECTION_OK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(UPDAPP_IMAGE, LOADMAP, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(UPDAPP_IMAGE, READONLYIMAGE, TRUE)

MMAP_UPDATE_PARTITION_INFO_OPT(DYNSW, ALLOW_UTA_BLOCK_IF_ACCESS, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(DYNSW, RO_BIT_CORRECTION_OK, TRUE)
MMAP_UPDATE_PARTITION_INFO_OPT(DYNSW, READONLYIMAGE, TRUE)
#endif  /* MMAP_INCLUDE_PARTITION_INFO */
