#============================================================================
# Description	: Generate the partition table file by souce code compile
# Author	: Hong Yu, hong.yu@intel.com
# Date		: 05/24/2015
#
# Usage		: 1. all the config xml comes from android/device/intel
#		: 2. sync up the files in scratterfile from modem
#		: 3. get the final prg file from the scatter_obj
#
# changed by WuLiangqing, wlq@rock-chips.com
# Description: integration into android
#============================================================================
#!/bin/bash

#echo -n "setup environment ..."
#. build/envsetup.sh >/dev/null && setpaths
#TARGET_PRODUCT=`get_build_var TARGET_PRODUCT`
#BUILD_WITH_UMS=`get_build_var BUILD_WITH_UMS`
#echo -n "FEAT_POW_EMIF_MAX_DDR2_FREQ=$FEAT_POW_EMIF_MAX_DDR2_FREQ"
#echo "done"

PrgSrcFilePath=device/rockchip/common/prg

ScatterSrcPath=${PrgSrcFilePath}/scatterfile
ScatterObjPath=$OUT/scatter_obj
ScatterConfigPath=device/rockchip/$TARGET_PRODUCT/partition
mkdir -p ${ScatterObjPath}

if [[ $BUILD_WITH_UMS == "true" ]]; then
PartitionFile=${ScatterConfigPath}/partition-separate.xml 
else
PartitionFile=${ScatterConfigPath}/partition-merge.xml
fi

# Generate memory layout header files
python ${PrgSrcFilePath}/memory_map.py -i ${PartitionFile} -b ${ScatterConfigPath}/8192_ram_layout.xml -d ${ScatterConfigPath}/flag_dependencies.xml -o ${ScatterObjPath}/memory_map.h -D ${ScatterObjPath}/ram_layout.h -c ${ScatterObjPath}/memory_map_description.h > null

# Build prggen tool
COMMON_DEFS="-m32 -DUNIX_BUILD -g -DA01_PTEST_SUPPORT -DA53_SUPPORT -DACC_DETECT_VIA_VU_MIC -DACC_METRICS_ENABLE -DACC_VUMIC_CONTROL -DACHIPID=agold620 -DAENEASPLUS_INCLUDE=0 -DAG620_ES2_0_DEFINED -DALWAYS_SILENT_RESET -DAMR_WB_SUPPORT -DANTENNA_SWITCH -DATC_DISABLE_BATT_CHECK -DATC_HW_TEST_IF -DATC_PBH_EXT_REC_SUPPORT -DATC_STK_LETTERCLASS_I -DAT_MEDRM_TEST -DAT_SIGNAL_ATTACH_IND_AVAILABLE -DAT_SIGNAL_IND_AVAILABLE -DAUDIO_DRV_CPS_IF_GENERATION_02 -DAUDIO_MM_PRESENT -DAUD_MASTER_VOLUME_CONCEPT -DAUD_RINGER -DAUD_TMP_USE_GTI_NVM_V2 -DBATTERY_MEASUREMENT -DBATTERY_MEASUREMENT_UMTS -DBMO_SUPPORT -DBOARDTYPE=1 -DBOOT_AND_MODE_MANAGER -DBT_SAP_SRV_AVAILABLE=1 -DCACHE_L2_DATA_ENABLE -DCATSYSTEM_ENABLED -DCAT_AUTO_ACCEPT -DCAT_AUTO_RESPONSE -DCAT_BUILD_2231 -DCAT_CACHE_LOAD_SUPPORT -DCAT_CID_DB_NOT_PRESENT -DCAT_CMM_ENABLED -DCAT_CTS_GPS -DCAT_DISPATCHER_UTA_FMR -DCAT_EM -DCAT_ENG_MODE_METRICS -DCAT_ETWS_SUPPORT -DCAT_EXT_CEER_INFO -DCAT_FEAT_LCS_IPV6_SUPPORT -DCAT_IPV6_SUPPORT -DCAT_LTE_POSITIONING_PROTOCOL -DCAT_MATCHING_ATC_FLAG -DCAT_MSIM_DVP -DCAT_MSIM_DVP_STATIONARY -DCAT_MUX_SUPPORT -DCAT_NET_FAST_DORMANCY_SUPPORT -DCAT_NVM_ASYNC_WRITE -DCAT_PSSI_XNVM_SUPPORT -DCAT_PS_NO_CARRIER_DISPLAY -DCAT_R7_SUPPORT -DCAT_R8_SUPPORT -DCAT_R9_SUPPORT -DCAT_SIM_TK_TERMINAL_PROFILE_SUPPORT -DCAT_SP6X60_NET_FAST_DORMANCY_SUPPORT -DCAT_STATIC_RXDIV -DCAT_STK_COMMAND_HANDLED_BY_MN_AND_SIM -DCAT_SYSTEM_DUAL_SIM_CONFIG -DCAT_SYSTEM_DUAL_SIM_PS_SUSPEND -DCAT_SYSTEM_DUMMYCB -DCAT_TRACE_DEBUG -DCAT_UMTS_SUPPORT -DCAT_UTA_BMM_SUPPORT -DCAT_XGOLD7160_SUPPORT_ONLY -DCAT_XMM2231_SUPPORT -DCBE_BUILDMODE_DEBUG -DCBS_DRX_ON -DCELL_BASED_FOFFS -DCELL_BASED_FOFFS_UMTS -DCELL_SPEC_TX_DIV_ENABLED -DCEU_PRESENT -DCFG_PLATFORM_CPP_INITIALISE_EXTERNAL -DCIPHER_A53 -DCIPHER_GEA1 -DCIPHER_GEA3 -DCLMK2_PS_CAPABILITY=SDL_false -DCMSP_CCBS_DISABLE -DCOMNEON_TARGET_ENV -DCONFIGURABLE_SW -DCPS_METRICS_SUPPORT -DCPU_CLOCK_HW_SCALING -DCPU_TASK_TRACKING_OFF -DCSE_MODULE_ENABLE -DDARP_SUPPORT_ENABLED=DARP_PHASE_2_ALWAYS_ON -DDEEP_SLEEP_ENABLED -DDIRECT_OFFLINE_MODE -DDISABLE_OTP_IMEI -DDMM_MAX_SIGNAL_CNT=1000 -DDM_ENGINEERING_MODE -DDONGLELESS_SEC_CONCEPT -DDRV_FEAT_AUDIO_MODEM_AVS -DDRV_LOWLEVEL_TESTINTERFACES -DDR_SM_STATUS_REPORT_IN_RAM -DDSDS_SR8148_ROP_2G -DDUAL_SIM -DDUAL_SIM_2G_3G_SUPPORT -DDUAL_SIM_SUPPORT -DDUMMY_2G_DIVERSITY_SUPPORT -DDWD_AUD_NEW_RC -DDWD_CENTRAL_STARTUP_HANDLING -DDWD_CURRENT_LOAD_MEASUREMENT -DDWD_GPRS -DDWD_QUADBAND -DDWD_TRIBAND -DDWD_UMTS -DDWD_USE_BURSTFLASH -DDWD_USE_DCACHE -DDYN_RXDIV_3G_SUPPORTED -DDYN_RXDIV_SUPPORTED -DEDPCCH_PWR_BOOST_ENABLED -DEDPDCH_PWR_INTERPOLATION_ENABLED -DEEP_PRESENT -DEEP_WITHOUT_STACKDATA -DEE_SIBLEY_LAYOUT -DEGAIM_NOT_SUPPORTED -DEGPRS_IR_SUPPORT -DEGPRS_SUPPORT -DEHPLMN_SUPPORTED -DEM_REPORTING_PERIOD_CHANGE=1 -DENABLE_FORCED_BALIST_DEBUG_OPTION -DENABLE_FORCED_SCELL_DEBUG_OPTION -DENABLE_LEGACY_MALLOC_DECLARATIONS -DENABLE_NEW_AT_PORTS -DENABLE_OVERLAPPING_PAGING -DENABLE_USE_HEAP_INTERFACE_MACROS -DENH_FDPCH_ENABLED -DETWS_ENABLED -DEVENT_GATEWAY_ENABLE -DEXTERNAL_SDL_DEBUG -DE_UMTS_MAX_NO_OF_ROHC_CTXT_SESSIONS=E_UMTS_MAX_NO_OF_ROHC_CTXT_SESSIONS_8 -DFAST_OOS_INDICATION_SUPPORT -DFCB_VCXO -DFDD_EXTENDED_SEARCH -DFDPCH_ENABLED -DFEAT_CAT_MUX_SUPPORT -DFEAT_FTLE_PRGGEN -DFEAT_MM_NO_RAT_SWITCH_CAUSE_12 -DFEAT_OPM_MEM_BLK_NUM_REL_EMMC_END -DFEAT_OPM_MEM_GPT_SUPPORT -DFEAT_OPM_MEM_MEX_AS_SECONDARY -DFEAT_OPM_MEM_SECTION_CERT -DFEAT_OPM_MEM_SECTION_CMM -DFEAT_OPM_MEM_SECTION_NVM_MIRROR -DFEAT_PRGGEN_VERSION_2 -DFEAT_SM_ACT_WITHOUT_RAB -DFEAT_VMM_AT_LOW_PHY_RAM -DFORCED_PS_CONN_REL -DFREQUENCY_MANAGER_AG620 -DFREQUENCY_MANAGER_ENABLE -DFREQUENCY_MANAGER_XMM6321 -DFREQUENCY_MANAGER_XMM6321A2 -DFSPEED_TEST_IF_ENABLED -DFTD_SUPPORT -DGLONASS_ENABLED -DGMSK_MULTISLOT_PWR_PROFILE=0 -DGMSK_TX_ONLY_SUPPORT -DGNSS_ENABLED -DGPRS -DGPS_ENABLED -DGRR_DSDS_SR8148_SUPPORT -DGRR_MON_ON -DGRR_MON_TARGET -DGSM_CALIB_TEST_IF_ENABLED -DGSM_TEST_IF_ENABLED -DGSM_TEST_INTERFACE -DGTC_DIVERT_ENABLED -DGTI_LLT_ENABLED -DGTI_MODULE_ENABLED -DGTI_NVM_INTERFACE_ENABLED -DGTU_ASYNC_WAKEUP_SUPPORT -DHARDENV -DHEAP_USAGE_REPORTING -DHSDPA_CATEGORY=14 -DHSDPA_HEADER_DATA_SPLIT_FORMAT -DHSDPA_URLC_RAW_TRACE -DHSPA_64QAM_DL_ENABLED -DHSPA_DTX_DRX_ENABLED -DHSPA_MAC_EHS_ENABLED -DHSPA_SLOT_FMT4_ENABLED -DHSUPA -DHSUPA_CATEGORY=6 -DHWTRC_PROTOCOL_VERSION -DI2C_MODULE_TEST -DI2C_TWO_CONTROLLERS -DINIT_RAM_EXTERNAL_SIZE_32M -DINTERRAT_SUPPORT -DIPR_L2P_HEADER_OFFSET=4 -DKEY_NO_FLIP_SUPPORT -DL1G_TWO_PS_ADV_ARP -DL1G_TWO_PS_ARP -DL1G_TWO_PS_SINGLE_FOI_TOI -DL1UD_ISR_UMTS_FRAME_INT_WATCHDOG -DL1UD_LIMIT_MAX_TX_POWER -DL1U_ONLY_SKIP_RF_BOARD_IDENTIFICATION -DL1_NEW_DRV_INTERFACE -DL1_R99 -DL1_RT_MEAS -DL1_TCLT_CPU_PERF_MON -DL1_WITH_PDCH_FILTER -DLLT -DLLT_ON_MESSAGE_TRACE -DLLT_V2 -DLOLLIPOP_PARTITION -DLOLLIPOP_PARTITION_LAYOUT -DLP_NO_ABORT_AID_REQ -DLTE_FREQ_SCAN_ALGO_RSSI_ENABLED -DMAX_SIM=2 -DMBIP_BMM_SUPPORT -DMEMORY_MAP_HEADER_GEN_ENABLED -DMETRICS_ENGINE_ENABLE -DMETRIC_DUAL_SIM -DMETRIC_ENG_MODE_ENABLE -DMETRIC_FM_CLIENT_ENABLE -DMMI_DUAL_SIM -DMMI_UTA -DMMU_STACK_PROTECTION -DMM_CMM_ENABLED -DMM_DUAL_SIM -DMM_FAST_OOS_INDICATION -DMM_HPLMN_SEARCH_IN_ROAMING_COUNTRY -DMM_NON_VLX_GPT_SUPPORT -DMM_RETRY_ON_REUSED_CONN_REL -DMM_STORED_FREQ_SCAN -DMN_ALERT_AFTER_PROGRESS -DMN_ALW_SEND_DIAG_IND -DMN_AUSTRALIA_000_IS_ECC -DMN_CCBS_NOT_SUPPORTED -DMN_CPHS_FOR_USIM_ENABLED -DMN_DEDICATED_MODE_STK_SETUP_CALL_ECC_CHECK -DMN_DISABLE_2G_CSD -DMN_SEND_NAS_SYNCH_IND -DMN_SUPPRESS_REG_INFO_FOR_PLMN_SEARCH -DMODEM_VIRTUAL_ANDROID_ENV -DMODEM_VIRTUAL_ENV -DMSAP_FAST_DORMANCY_SUPPORTED -DMSAP_FDN_CHECK_SMS_SCA_ENABLE -DMSAP_IFGEN_02_DRV -DMSAP_RESMEM -DMSC3X_SUPPORT -DMSIM_DVP_ENHANCED_SUPPORT -DMSIM_DVP_STATIONARY_SUPPORT -DMSIM_DVP_SUPPORT -DMS_ASSERT -DMS_ERROR_SEVERITY=3 -DMS_IPV6_SUPPORT -DMS_NO_CSD_IN_GSM -DMS_OS_CRITICAL_SECTION_SUPPORT=1 -DMTC_SUPPORTED=1 -DMULTI_SLOT_CLASS_EGPRS=12 -DMULTI_SLOT_CLASS_GPRS=12 -DNATIVE_DMA_LINUX_PRESENT -DNATIVE_I2C_LINUX_PRESENT -DNATIVE_USB_LINUX_PRESENT -DNOC_TRAP_STORE_EXCEPTION -DNO_EPOWER -DNO_RESTART_ON_CCI_ERROR -DNO_SOUNDER -DNSP_SUPPORTED -DNVM_PARTITION_SEGGREGATION -DNVM_PRESENT -DNVRAM_SUPPORT -DNVR_STARTUP_MODE_SUPPORT -DNVR_USE_PS_GROUP_DEF -DOM_BATTERY_CONSUMPTION_OPTIMIZATION_SUPPORTED -DOM_DRV_CPS_IF_GENERATION_02 -DOM_DUAL_SIM -DOM_POWER_OFF_BY_APPLICATION -DOM_RM_PRIORITY_MODE_DISABLE -DONE_SEC_CAL_RX -DONE_SEC_CAL_TX -DOPM_BYPASS_STARTUP_DET -DPAGING_STRUCTS_IN_CACHE -DPARTIAL_DISABLE_IRQ_AVOID_EXTEND -DPA_BOOTCODE_PA_EN_B5_ON_BANDSELECT -DPBM_MEM_PROTECT_ABOUT_IRQ -DPB_RAM_CACHE=75 -DPCH_NO_DEFAULT_BEARER_CONTEXT -DPCL_REG_INLINE_DISABLED -DPCM_PLAYER -DPDCP_PC_RFC2507 -DPDCP_PC_RFC3095_EFFNET -DPMI_SUPPRESS_SEND_OM_CONTROL_REQ -DPMI_UTA_SYS -DPMU_REGISTER_TESTINTERFACE -DPOWER_CONCEPT_3 -DPOWER_CONCEPT_3_PLUS -DPOWER_CONTROL_PC4_ONLY -DPOWER_MANAGEMENT_USE_PRH_IF -DPOW_AND_PSV_INTERFACE -DPOW_DVS_ENABLE -DPOW_SAVE -DPRH_CPU_4_LEVEL_CPUFREQ_SUPPORT -DPSHO_I2_SUPPORT=1 -DPSHO_SUPPORT -DPSK8_MULTISLOT_PWR_PROFILE=2 -DPTF_HEAP_NOF_DEBUG_BLOCKS=1500 -DPTF_HEAP_SIZE=3145728 -DPTF_TIME_SUPPORT -DPTP -DR4_SUPPORT -DR5_SUPPORT -DR6_SUPPORT -DR7_SUPPORT -DR8_SUPPORT -DR99_SUPPORT -DR9_SUPPORT -DRECOVERY_MECHANISM_SUPPORTED -DREPEATED_ACCH_CAP_ENABLE -DREP_FACCH_SACCH -DRF_AGOLD620_ES1 -DRF_COMPENSATION -DRF_DEV_CELL_BASED_FOFFS -DRF_ENGINE_VARIANT_C2_1 -DRF_FE_AG620_GRANITE_FEID_284 -DRF_INIT_CFG_FIXED_ADDRESS -DRF_RAMPS_IN_EEP -DROHC_DEBUG_ON -DRPCRIL_MULTISIM -DRPC_ENABLED -DRPC_REMOVE_SECURITY_DUMMY_CB -DRPC_UTA_BMM_SUPPORT -DRR_FAST_OOS_INDICATION -DRTC_ATC_EVENT -DRTC_CALIBRATION -DRTC_DRV_CPS_IF_GENERATION_02 -DRTT_PRESENT -DSBC_ENCODER -DSDL_SOFT_TIMER_SUPPORT=1 -DSECOND_DRX_PCH_ENABLED -DSEC_PRESENT -DSEL_RABREESTAB_SUP -DSEPARATE_AT_BLOCK -DSERIAL_DMA -DSF_3G_SOC -DSF_MMIO_SSE_COPY_32BIT_ALIGN_WA -DSGOLD3_DMA_PSV -DSHOW_EXTRA_TRACE_MSG -DSIB11BIS_ENABLED -DSIC_BASED_MMI -DSIC_SMS_HANDLER -DSILENT_RESET -DSIM_BASED_ENS_RAT_SUPPORTED -DSINGLE_ANTENNA_SUPPORT -DSINGLE_GPTU_CONFIGURATION -DSIO_3G_BCH_SUPPORT -DSIO_AT_DEVICE=IO_UART_NAME_0 -DSIO_BT_AVAILABLE=0 -DSIO_DISTRIBUTED_SW=1 -DSIO_DS_DEVICE=IO_UART_NAME_0 -DSIO_ENHANCED_EXIT=1 -DSIO_FLEXIBLE_DEVICES_AVAILABLE -DSIO_HMC_SUPPORTED=0 -DSIO_HMC_USE_HW_LINES=0 -DSIO_IS_DTM_ACTIVE=2 -DSIO_LT_GET_TRACE_BUFFER_SUPPORT -DSIO_MUX_AVAILABLE=1 -DSIO_OPT_PPP_AVAILABLE=1 -DSIO_OPT_PPP_OBSOLETE_ACTIVATION=1 -DSIO_PTP_DEVICE=IO_UART_NAME_0 -DSIO_TRACE_DEVICE=IO_UART_NAME_1 -DSIO_USE_DATA_CACHE=1 -DSIO_USE_GLUE_CONCEPT=1 -DSIO_USE_SELECT_CONCEPT=1 -DSIO_USE_SOCKET_CONCEPT=1 -DSI_APPLICATION_IND_ALLOWED -DSI_CARD_IND_ALLOWED -DSI_CHECK_CALL_TYPE_FOR_DELAY_REFRESH -DSI_CHECK_SIMID -DSI_CUST_PROF_PRJ=xmm6321 -DSI_DONT_FETCH_WITHOUT_PROACTIVE_CLIENT -DSI_DR_NOT_PRESENT -DSI_DUAL_SIM -DSI_EXT_TP_ALLOWED -DSI_GEN_STK_ENFORCED_SUPPORT -DSI_IMSI_IND_ALLOWED -DSI_MI_NOT_PRESENT -DSI_NO_CC_FOR_SUBADDRESS -DSI_NO_IMMEDIATE_RESPONSE_TAG -DSI_PB_BYPASS -DSI_PB_CACHE_ALLOWED -DSI_RAM_CACHE=15 -DSI_SEND_GEN_SIGNAL_FLAG=TRUE -DSI_SIM_ERROR_AUTO_RESTART -DSI_SMS_RAM_CACHE -DSI_STK_FETCH_DISABLED_DEFAULT -DSI_STK_POLL_INTERVAL_DELTA=20 -DSI_WAIT_TP_DURATION=300 -DSMPOWER3 -DSMS107980_PCLINT_WARN -DSNP_PC_RFC2507 -DSNP_PC_RFC3095_EFFNET -DSTK_LTE_NEW_BUFFER_CONCEPT_FEATURE_FLAG -DSTK_MAP_USSD_CB_DCS -DSTK_USSD_DONT_MAP_LANG_UNSPEC -DST_CAPCOM_WAKEUP_WORKAROUND -DSWU_ENABLED -DSW_RESET -DSW_RESET_CHV -DSYSTEM_TIMER_4KHZ -DSYS_IR_USE_LWPPP=1 -DSYS_SCC_MAX_CHANNEL_NO=55 -DSYS_SIO_NUMBER_OF_MUX_CHANNELS=8 -DSYS_TIC_MAX_TIMERS=100 -DTARGET -DTCP_HEADER_COMPR -DTEST_AFC_REPORTING -DTIMESERVICES_RTT_IN_TS -DTRACE_DEBUG_MONITOR_SDL_ENABLED -DTRAP_HANDLING -DTU_8_MON_CONCEPT -DTU_CLASS12 -DTU_WITH_BATTERY_MEASUREMENT -DTX_INCLUDE_USER_DEFINE_FILE -DUAS_IOT_SUPPRESSEVENTS_2X -DUEA2_ENABLED -DUGDCI_HW -DUIA2_ENABLED -DUICC_CC_IN_POLARITY -DUICC_DUAL_SIM_SUPPORT_DUALBLOCK -DUICC_DUAL_SIM_SUPPORT_STACKIF -DUICC_ENABLE_IN_OUT_DETECTION -DUICC_ENABLE_T1_APRE_MODE -DUICC_IPDB_USIM_T1_WORK_AROUND -DUMTS -DUMTS_AENEAS -DUMTS_CALIBRATION_IF_ENABLED -DUMTS_CONFIGURATION_IF_ENABLED -DUMTS_DISABLE_LOSSLESS_SRNS_RELOCATION -DUMTS_ETFCI_STAT -DUMTS_FW_TRACING -DUMTS_HC_CONTEXT_SPACE=E_UMTS_HC_CONTEXT_SPACE_16384 -DUMTS_HSDPA -DUMTS_HSUPA -DUMTS_RLC_AM_BUFFER_SIZE=E_UMTS_RLC_AM_BUFFER_SIZE_400 -DUMTS_RLC_AM_BUFFER_SIZE=E_UMTS_RLC_AM_BUFFER_SIZE_750 -DUMTS_RLC_MAX_AM_ENTITY=E_UMTS_RLC_MAX_AM_ENTITY_8 -DUMTS_SUPPORT -DUMTS_TEST_IF_ENABLED -DURRCM_MEAS_TRACE_DISABLED -DURRC_FAST_DORMANCY -DURRC_FAST_DORMANCY_PHASE_II -DURRC_MEDRM_TEST -DUSB_VBUS_EINT_ACTIVE_LOW -DUSE_RTOS_IDLE_THREAD -DUSE_SECURITY_DATA -DUSIF_HW_BAUD_TABLE=104 -DUSIF_HW_SINGLE_IRQ_VECTOR -DUSIF_REG_INLINE_DISABLED -DUTA -DUTA_BUILD_VERSION=0 -DUTA_COMPILER_ICC -DUTA_DISPLAY_0_HEIGHT=480 -DUTA_DISPLAY_0_WIDTH=320 -DUTA_DISPLAY_COUNT=1 -DUTA_INET_IPV6_FEAT -DUTA_MAJOR_VERSION=2 -DUTA_MINOR_VERSION=0 -DUTA_NET_FAST_DORMANCY_SUPPORT -DUTA_OS -DUTA_OS_OBJECT_NAME_SUPPORT -DUTA_OS_THREADX -DUTA_OS_TIMER_IN_TSDRIVER -DUTA_PLATFORM_XMM6180 -DUTA_SIM_TK_PROACTIVE_COMMANDS_HANDLED_BY_MODEM -DUTA_SIM_TK_RAW_ACCESS -DUTA_SIM_TK_TERMINAL_PROFILE_SUPPORT -DUTA_TARGETSYSTEM_HW -DVAMOS_I_ENABLED -DVMM_COREDUMP_SUPPORT -DVMM_MOBILEVISOR -DVMM_ON_XMM6310 -DVRL_PARTITION_ENABLED -DXDR_SUPPORTED=0 -DXENV -DXG632_ES2_0_DEFINED -DXL1_IQ_TRACE -DXL1_TEST_IF_ENABLED -DXMM6180_REMOVE_WHEN_UPDATED_TO_NEW_ARCHITECTURE -DXMM6260_CPS_ES2 -DXMM6260_DCXO_HW_SUPPORT -DXMM6260_SUE2_A1 -DXMM6260_SUE2_A1_PMU2 -DXMM6310_ES1_01_SUPPORT -DXMM6310_HCI -DXMM6321_DCXO_HW_SUPPORT -DXMM6321_POW_SLEEP_WA_FIXES -DXUSE_GENERIC_FUNC -D_64K_DYN_EEPROM -D_65536MBIT_FLASH -D_8192MBIT_EXT_RAM -D_CBE_LIBNAME_=\"\" -D_THREADXTYPES_H -D__x86 -DPRGGEN_VERSION=2 -DBOOT_USE_VERSIONINFO -DFEAT_VMM_SUPPORT -DFEAT_FLASH_WRITE_PROTECT_ENABLED -DFEAT_OPM_MEM_GPT_SUPPORT -DFEAT_OPM_MEM_SECTION_NVM_MIRROR -DFEAT_OPM_MEM_BLK_NUM_REL_EMMC_END -DPRGGEN_VERSION=2 -DBOOT_USE_VERSIONINFO -DFEAT_VMM_SUPPORT -DFEAT_FLASH_WRITE_PROTECT_ENABLED -DFEAT_OPM_MEM_GPT_SUPPORT -DFEAT_OPM_MEM_SECTION_NVM_MIRROR -DFEAT_OPM_MEM_BLK_NUM_REL_EMMC_END "
C_SHA1_DEFS="-DCFG_PLATFORM_CALL_PREPARE_CPP_INITIALISE -DEGW_MULTI_SIM -DEGW_STACK_INSTANCES=2 -DINTERNAL_POLYRINGER -DMSAP_FEAT_BOOT_AND_MODE_MANAGER -DMSAP_MSIM_DVP -DMSAP_MSIM_DVP_ENHANCED -DMSAP_TEST_MODE_ACTIVATION -DPLATFORM_PREPARE_CPP_INITIALISE -DTX_SSE_SUPPORT -DUGDCI_TRACE "

g++ ${COMMON_DEFS} \
-I${ScatterSrcPath}/stack-interface/globals \
-I${ScatterSrcPath}/SF_3GR \
-I${ScatterSrcPath}/sf_3gr_soc \
-I${ScatterSrcPath} \
-I${ScatterSrcPath}/tools/prggen \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/src \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/inc \
-I${ScatterSrcPath}/nv_memory_driver/inc \
-I${ScatterSrcPath}/nv_memory_driver/ftle/src \
-I${ScatterObjPath} \
-c ${ScatterSrcPath}/tools/prggen/prggen.cpp \
-o ${ScatterObjPath}/prggen.o > null

g++ ${COMMON_DEFS} ${C_SHA1_DEFS} \
-I${ScatterSrcPath}/stack-interface/globals \
-I${ScatterSrcPath}/SF_3GR \
-I${ScatterSrcPath}/sf_3gr_soc \
-I${ScatterSrcPath} \
-I${ScatterSrcPath}/tools/prggen \
-I../../msw_tools/FlashTool/libFlsTool/src \
-I../../msw_tools/FlashTool/libFlsTool/inc \
-I../../mhw_drv_src/nv_memory_driver/inc \
-I../../mhw_drv_src/nv_memory_driver/ftle/src \
-I${ScatterObjPath} \
-UNAND_PRESENT \
-c ${ScatterSrcPath}/tools/FlashTool/libFlsTool/src/c_sha1.c \
-o ${ScatterObjPath}/c_sha1.o > null

g++ ${COMMON_DEFS} \
-I${ScatterSrcPath}/stack-interface/globals \
-I${ScatterSrcPath}/SF_3GR \
-I${ScatterSrcPath}/sf_3gr_soc \
-I${ScatterSrcPath} \
-I${ScatterSrcPath}/tools/prggen \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/src \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/inc \
-I${ScatterSrcPath}/nv_memory_driver/inc \
-I${ScatterSrcPath}/nv_memory_driver/ftle/src  \
-I${ScatterObjPath} \
-UNAND_PRESENT \
-c ${ScatterSrcPath}/tools/FlashTool/libFlsTool/src/MemoryStream.cpp \
-o ${ScatterObjPath}/MemoryStream.o > null

g++ ${COMMON_DEFS} \
-I${ScatterSrcPath}/stack-interface/globals \
-I${ScatterSrcPath}/SF_3GR \
-I${ScatterSrcPath}/sf_3gr_soc \
-I${ScatterSrcPath} \
-I${ScatterSrcPath}/tools/prggen \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/src \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/inc \
-I${ScatterSrcPath}/nv_memory_driver/inc \
-I${ScatterSrcPath}/nv_memory_driver/ftle/src \
-I${ScatterObjPath} \
-UNAND_PRESENT \
-c ${ScatterSrcPath}/tools/FlashTool/libFlsTool/src/PrgHandler.cpp \
-o ${ScatterObjPath}/PrgHandler.o > null 

g++ ${COMMON_DEFS} \
-I${ScatterSrcPath}/stack-interface/globals \
-I${ScatterSrcPath}/SF_3GR \
-I${ScatterSrcPath}/sf_3gr_soc \
-I${ScatterSrcPath} \
-I${ScatterSrcPath}/tools/prggen \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/src \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/inc \
-I${ScatterSrcPath}/nv_memory_driver/inc \
-I${ScatterSrcPath}/nv_memory_driver/ftle/src \
-I${ScatterObjPath} \
-UNAND_PRESENT \
-c ${ScatterSrcPath}/tools/FlashTool/libFlsTool/src/PrgSequencer.cpp \
-o ${ScatterObjPath}/PrgSequencer.o > null

g++ ${COMMON_DEFS} \
-I${ScatterSrcPath}/stack-interface/globals \
-I${ScatterSrcPath}/SF_3GR \
-I${ScatterSrcPath}/sf_3gr_soc \
-I${ScatterSrcPath} \
-I${ScatterSrcPath}/tools/prggen \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/src \
-I${ScatterSrcPath}/tools/FlashTool/libFlsTool/inc \
-I${ScatterSrcPath}/nv_memory_driver/inc \
-I${ScatterSrcPath}/nv_memory_driver/ftle/src \
-I${ScatterObjPath} \
-UNAND_PRESENT \
-c ${ScatterSrcPath}/tools/FlashTool/libFlsTool/src/FileIO.cpp \
-o ${ScatterObjPath}/FileIO.o > null

g++ -m32 -static-libgcc -L. ${ScatterObjPath}/prggen.o ${ScatterObjPath}/c_sha1.o ${ScatterObjPath}/MemoryStream.o ${ScatterObjPath}/PrgHandler.o ${ScatterObjPath}/PrgSequencer.o ${ScatterObjPath}/FileIO.o -o ${ScatterObjPath}/prggen > null

#./prggen <Hex2FlsToolPath> <VOBGlobalPath> <BoardId> <ScatterObjPath> <IntStage> <MM_DEFS> HexInput [HexInput...]
Hex2FlsToolPath=vendor/intel/tools/FlsTool
VOBGlobalPath=$OUT
BoardId=board_sf_3gr
IntStage=MEX
MM_DEFS="FEAT_PRGGEN_VERSION_2 LOLLIPOP_PARTITION_LAYOUT VRL_PARTITION_ENABLED NVM_PARTITION_SEGGREGATION FEAT_OPM_MEM_SECTION_CERT FEAT_OPM_MEM_SECTION_CMM FEAT_OPM_MEM_GPT_SUPPORT MM_NON_VLX_GPT_SUPPORT FEAT_OPM_MEM_SECTION_NVM_MIRROR FEAT_OPM_MEM_MEX_AS_SECONDARY FEAT_VMM_AT_LOW_PHY_RAM FEAT_OPM_MEM_BLK_NUM_REL_EMMC_END FEAT_FTLE_PRGGEN FEAT_PRGGEN_VERSION_2 LOLLIPOP_PARTITION_LAYOUT VRL_PARTITION_ENABLED NVM_PARTITION_SEGGREGATION FEAT_OPM_MEM_SECTION_CERT FEAT_OPM_MEM_SECTION_CMM FEAT_OPM_MEM_GPT_SUPPORT MM_NON_VLX_GPT_SUPPORT FEAT_OPM_MEM_SECTION_NVM_MIRROR FEAT_OPM_MEM_MEX_AS_SECONDARY FEAT_VMM_AT_LOW_PHY_RAM FEAT_OPM_MEM_BLK_NUM_REL_EMMC_END FEAT_FTLE_PRGGEN"
HexInput="vendor/intel/images/hex/SF_3GR.ihex"
PrgLog=${ScatterObjPath}/prggen.log

${ScatterObjPath}/prggen ${Hex2FlsToolPath} ${VOBGlobalPath} ${BoardId} ${ScatterObjPath} ${IntStage} ${MM_DEFS} ${HexInput} > null
